config/routes.rb
Rails.application.routes.draw do
  post 'rents/rent_confirmation', to: 'rents#rent_confirmation', as: 'rent_confirmation'
  get 'rents/confirmation_page'
  post 'rents/:address_id', to: 'rents#set_address', as: 'set_address'
  get 'rents/addressToRent'
  get 'games/myGames'
  resources :rent_games
  root to: 'games#index'
  resources :addresses
  get 'control_users/index'
  devise_for :users
  resources :rents
  resources :games
  resources :categories
  resource :carts, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/rent.rb
class Rent < ApplicationRecord
  belongs_to :user
  belongs_to :address, optional: true
  has_many :rent_games
  # has_many :games, through: :rent_games
  before_save :update_total
  before_create :update_status

  def calculate_total
    rent_games.collect { |item| item.game.rentPrice * item.week }.sum
  end
  
  private
  
  def update_status
    self.status = 'In progress' if status == nil?
  end

  def update_total
    self.totalValue = calculate_total
  end
end

app/controllers/rents_controller.rb
class RentsController < ApplicationController
    before_action :set_rent, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!
    before_action :address_params, only: [:set_address]

    def index
      if current_user.role == 'admin'
        @rents = Rent.all.where(status: 'finish')
      end
      if current_user.role == 'normal_user'
        @rents = Rent.all.where(user_id: current_user.id).where(status: 'finish')
      end
    end

    def show
    end
  
    def new
      @rent = Rent.new
    end
  
    def edit
    end

    def set_address
      @rent = current_rent
      @rent.address = @address
      @rent.save
      redirect_to rents_confirmation_page_path
    end

    def rent_confirmation
      @rent = current_rent
      @rent.status = 'finish'

      respond_to do |format|
        @rent.rent_games.each do |item|
          item.game.status = false
          item.game.save
        end
        if @rent.save
          format.html { redirect_to root_path, notice: 'Aluguel realizado com sucesso!'}
          session.delete(:rent_id)
        end
      end
    end

    def confirmation_page
      @rent = current_rent
    end

    def addressToRent
      @addresses = current_user.addresses
    end

    def create
        @rent = Rent.new(rent_params)
    
        respond_to do |format|
            if @rent.save
                format.html { redirect_to @rent, notice: 'Rent was successfully created.' }
                format.json { render :show, status: :created, location: @rent }
            else
                format.html { render :new }
                format.json { render json: @rent.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @rent.update(rent_params)
                format.html { redirect_to @rent, notice: 'Rent was successfully updated.' }
                format.json { render :show, status: :ok, location: @rent }
            else
                format.html { render :edit }
                format.json { render json: @rent.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
        @rent.destroy
        respond_to do |format|
            format.html { redirect_to rents_url, notice: 'Rent was successfully destroyed.' }
            format.json { head :no_content }
        end
    end

    private

    def set_rent
        @rent = Rent.find(params[:id])
    end

    def rent_params
        params.require(:rent).permit(:time, :date, :totalValue)
    end

    def address_params
      @address = Address.find(params[:address_id])
    end

end

app/helpers/rents_helper.rb
module RentsHelper
end

app/views/rents/_form.html.erb
<%= form_with(model: rent, local: true) do |form| %>
  <% if rent.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(rent.errors.count, "error") %> prohibited this rent from being saved:</h2>

      <ul>
      <% rent.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :week %>
    <%= form.number_field :week %>
  </div>

  <div class="field">
    <%= form.label :totalValue %>
    <%= form.text_field :totalValue %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/rents/addressToRent.html.erb
<div class="container container-index-address">
  <header class="title has-text-centered">Endereço para Entrega</header>
  <div class="columns is-multiline">
    <% @addresses.each do |address| %>
      <div class="column column-address">
        <div class="box box-address">
          <div class="level"><strong>CEP:</strong><%=address.cep %></div>
          <div class="level"><strong>Endereço:</strong><%=address.address %></div>
          <div class="level"><strong>Bairro:</strong><%=address.district %></div>
          <div class="level"><strong>Cidade:</strong><%=address.city %></div>
          <div class="level"><strong>Complemento:</strong><%=address.complement %></div>
          <div class="level">
            <%= link_to 'Selecionar', set_address_path(:address_id => address.id), class:'button is-warning is-fullwidth is-medium', method: :post %>
          </div>
        </div>
      </div>
    <%end %>
  </div>
</div>

app/views/rents/confirmation_page.html.erb
<div class="container">
  <header class="title has-text-centered">Confirmação de Aluguel</header>
  <div class="columns">
    <div class="column is-three-fifths">
      <table class="table is-striped is-hoverable is-narrow is-fullwidth">
        <thead>
        <tr>
          <th>Capa</th>
          <th>Nome</th>
          <th>Valor do Alguel</th>
          <th>Semana(s)</th>
          <th>Subtotal</th>
        </tr>
        </thead>
        <tbody>
          <% @rent.rent_games.each do |item| %>
            <tr class="row-list-game">
              <td class="td"><figure class="image is-64x64"><%=image_tag(item.game.image.to_s) %></figure></td>
              <td class="td"><%=item.game.name %></td>
              <td class="td"><%=number_to_currency(item.game.rentPrice, unit: "R$", separator: ",", delimiter:"") %></td>
              <td class="td"><%=item.week %></td>
              <td class="td"><%=number_to_currency(item.subtotal, unit: "R$", separator: ",", delimiter:"") %></td>
            </tr>
          <%end %>
        </tbody>
      </table>
    </div>
    <div class="column is-centered">
      <div class="level"><strong>CEP:</strong><%=@rent.address.cep %></div>
      <div class="level"><strong>Endereço:</strong><%=@rent.address.address %></div>
      <div class="level"><strong>Bairro:</strong><%=@rent.address.district %></div>
      <div class="level"><strong>Cidade:</strong><%=@rent.address.city %></div>
      <div class="level"><strong>Complemento:</strong><%=@rent.address.complement %></div>
      <hr/>
      <div class="level"><strong>Total:</strong><%=number_to_currency(@rent.totalValue, unit: "R$", separator: ",", delimiter:"") %></div>
      <%=link_to 'Confirmar', rent_confirmation_path, class:'button is-success is-fullwidth', method: :post %>
    </div>
  </div>
</div>

app/views/rents/edit.html.erb
<h1>Editing Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Show', @rent %> |
<%= link_to 'Back', rents_path %>

app/views/rents/index.html.erb
<div class="container container-index-rent">
  <header class="title has-text-centered">Lista de Aluguéis Realizados</header>
  <table class="table is-striped is-hoverable is-narrow is-fullwidth">
    <thead>
    <tr>
      <th>#</th>
      <th>Valor Total</th>
      <th></th>
    </tr>
    </thead>
    <tbody>
    <% @rents.each do |rent| %>
      <tr>
        <td class="td"><%=rent.id %></td>
        <td class="td"><%=number_to_currency(rent.totalValue, unit: "R$", separator: ",", delimiter:"")%></td>
        <td class="td">
          <div class="buttons are-normal">
            <%=link_to rent_path(rent), class:'button is-info' do%>
              <span class="icon">
                <i class="far fa-eye"></i>
              </span>
              &nbsp;&nbsp;Detalhes
            <%end %>
          </div>
        </td>
      </tr>
    <%end %>
    </tbody>
  </table>
</div>

app/views/rents/new.html.erb
<h1>New Rent</h1>

<%= render 'form', rent: @rent %>

<%= link_to 'Back', rents_path %>

app/views/rents/show.html.erb
<div class="container">
  <header class="title has-text-centered">Detalhes do Aluguel</header>
  <br>
  <div class="columns">
    <div class="column is-three-fifths">
      <table class="table is-striped is-hoverable is-narrow is-fullwidth">
        <thead>
        <tr>
          <th>Capa</th>
          <th>Nome</th>
          <th>Valor do Alguel</th>
          <th>Semana(s)</th>
          <th>Subtotal</th>
        </tr>
        </thead>
        <tbody>
          <%@rent.rent_games.each do |item| %>
            <tr class="row-list-game">
              <td class="td"><figure class="image is-64x64"><%=image_tag(item.game.image.to_s) %></figure></td>
              <td class="td"><%=link_to item.game.name, games_path(item.game), class: 'button is-link' %></td>
              <td class="td"><%=number_to_currency(item.game.rentPrice, unit: "R$", separator: ",", delimiter:"")%></td>
              <td class="td"><%=item.week %></td>
              <td class="td"><%=number_to_currency(item.subtotal, unit: "R$", separator: ",", delimiter:"")%></td>
            </tr>
          <%end %>
          <tr>
            <th>Total do Aluguel:</th>
            <th></th>
            <th></th>
            <th></th>
            <th><%=number_to_currency(@rent.totalValue, unit: "R$", separator: ",", delimiter:"")%></th>
          </tr>
        </tbody>
      </table>
    </div>
    <div class="column is-centered">
      <div class="level"><strong>CEP:</strong><%=@rent.address.cep %></div>
      <div class="level"><strong>Endereço:</strong><%=@rent.address.address %></div>
      <div class="level"><strong>Bairro:</strong><%=@rent.address.district %></div>
      <div class="level"><strong>Cidade:</strong><%=@rent.address.city %></div>
      <div class="level"><strong>Complemento:</strong><%=@rent.address.complement %></div>
    </div>
  </div>
</div>