config/routes.rb
Rails.application.routes.draw do
  post 'rents/rent_confirmation', to: 'rents#rent_confirmation', as: 'rent_confirmation'
  get 'rents/confirmation_page'
  post 'rents/:address_id', to: 'rents#set_address', as: 'set_address'
  get 'rents/addressToRent'
  get 'games/myGames'
  resources :rent_games
  root to: 'games#index'
  resources :addresses
  get 'control_users/index'
  devise_for :users
  resources :rents
  resources :games
  resources :categories
  resource :carts, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/game.rb
class Game < ApplicationRecord
  mount_uploader :image, ImageUploader
  belongs_to :user
  belongs_to :category
  has_many :rent_games
  # has_many :rents, through: :rent_games
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
    before_action :set_game, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user!, except: [:index]

    def index
        @games = Game.all.where(status: 'true')
    end

    def show
        @rent_games = current_rent.rent_games.new
    end

    def myGames
        @games = current_user.games.where(visible: true)
    end

    def new
      @game = Game.new
      @categories = Category.all
    end

    def edit
      @categories = Category.all
    end

    def create
        @game = Game.new(game_params)
        @game.user_id = current_user.id
        @game.status = true
        respond_to do |format|
            if @game.save
                format.html { redirect_to @game, notice: 'Game was successfully created.' }
                format.json { render :show, status: :created, location: @game }
            else
                format.html { render :new }
                format.json { render json: @game.errors, status: :unprocessable_entity }
            end
        end
    end

    def update
        respond_to do |format|
            if @game.update(game_params)
                format.html { redirect_to @game, notice: 'Game was successfully updated.' }
                format.json { render :show, status: :ok, location: @game }
            else
                format.html { render :edit }
                format.json { render json: @game.errors, status: :unprocessable_entity }
            end
        end
    end

    def destroy
      begin
        @game.destroy
        respond_to do |format|
          format.html { redirect_to games_url, notice: 'Jogo foi foi excluído com  sucesso!' }
          format.json { head :no_content }
        end
      rescue
        format.html { redirect_to games_url, notice: 'Ação não pode ser executada por referência do jogo em um alguel!' }
      end

    end

    private

    def set_game
        @game = Game.find(params[:id])
    end

    def game_params
        params.require(:game).permit(:name, :description, :rentPrice, :image, :category_id)
    end
end

app/helpers/games_helper.rb
module GamesHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name, 'Nome' , class:'label', for: 'name'%>
    <div class="control">
      <%= form.text_field :name , class:'input', id: 'name', required:'true'%>
    </div>
  </div>

  <div class="field">
    <%= form.label 'Preço para aluguel', class: 'label', for: 'rentPrice'%>
    <p class="control">
      <%= form.text_field :rentPrice, class: 'input', id: 'rentPrice', placeholder:"Padrão Americanos 0.00", required: 'true'%>
    </p>
  </div>

  <div class="field is-horizontal">
    <div class="field-body">
      <div class="field">
        <%= form.label 'Categoria', class: 'label', for: 'category' %>
        <div class="control">
          <div class="select">
           <%= collection_select(:game, :category_id, @categories, :id, :name, {}, {id: 'category' }) %>
          </div>
        </div>
      </div>
      <div class="field">
        <%= form.label 'Capa do Jogo', class:'label'%>
        <div class="file">
          <label class="file-label">
            <%= form.file_field :image, class:'file-input', onchange:'inputFileName()', id:"image" %>
            <span class="file-cta">
              <span class="file-icon">
                <i class="fas fa-upload"></i>
              </span>
              <span class="file-label">
                Escolha uma imagem
              </span>
               </span>
              <span class="file-name" id="file-name" style="display: none">
            </span>
          </label>
        </div>
      </div>
    </div>
  </div>

  <div class="field">
    <%= form.label 'Descrição', class: 'label', for: 'description' %>
    <div class="control">
      <%= form.text_area :description, class:'textarea', id:'description', required:'true', placeholder:'Description the game'%>
    </div>
  </div>

  <div class="actions">
    <div class="control">
      <%= form.submit class: 'button is-success is-fullwidth'%>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<div class="container container-form-game">
<header class="title has-text-centered">Editar Jogo</header>
  <%= render 'form', game: @game %>
</div>

<!--<%#= link_to 'Show', @game %> |-->
<%#= link_to 'Back', games_path %>

app/views/games/index.html.erb
<div class="container container-index">
  <div class="columns is-multiline">
    <% @games.each do |game| %>
      <%#if @game.user.id != current_user.id || current_user == nil %>
        <div class="column column-game">
          <div class="box box-game">
            <div class="level has-text-centered">
              <%=link_to game.name, game_path(game), class:'title is-6 title-game' %>
            </div>
            <div class="level">
              <figure class="image is-90x64">
                <%=image_tag(game.image.to_s) %>
              </figure>
            </div>
          </div>
        </div>
      <%#end %>
    <% end %>
  </div>
</div>

<!--<br>-->

<%#= link_to 'New Game', new_game_path %>

app/views/games/myGames.html.erb
<div class="container">
  <header class="title has-text-centered">Meus Jogos <%=link_to new_game_path, class:'button is-success' do %>
      <span class="icon">
        <i class="fas fa-plus-circle"></i>
      </span>
    <%end %>
  </header>
<table class="table is-striped is-hoverable is-narrow is-fullwidth">
    <thead class="has-centered">
      <tr>
        <th class="has-centered">Capa</th>
        <th class="has-centered">Nome</th>
        <th class="has-centered">Valor do Aluguel</th>
        <th class="has-centered">Categoria</th>
        <th class="has-centered">Opções</th>
      </tr>
    </thead>
    <tbody>
      <% @games.each do |game| %>
        <tr class="row-list-game">
          <td class="td">
            <figure class="image is-64x64"><%= image_tag(game.image.to_s) %></figure>
          </td>
          <td class="td"><%=game.name %></td>
          <td class="td"><%=number_to_currency(game.rentPrice, unit: "R$", separator: ",", delimiter:"")%></td>
          <td class="td"><%=game.category.name %></td>
          <td class="td">
            <div class="buttons are-normal">
            <%= link_to game, class:'button is-info' do %>
                <span class="icon">
                  <i class="fas fa-info-circle"></i>
                </span>
              <%end %>
              <%= link_to edit_game_path(game), class: 'button is-warning' do %>
                <span class="icon">
                  <i class="fas fa-edit"></i>
                </span>
              <%end %>
              <%= link_to game, method: :delete, data: {confirm: 'Are you sure?'}, class: 'button is-danger' do %>
                <span class="icon">
                  <i class="far fa-times-circle"></i>
                </span>
              <%end %>
            </div>
          </td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/games/new.html.erb
<div class="container container-form-game">
  <header class="title has-text-centered">Cadastro de Jogo</header>
  <%= render 'form', game: @game %>
</div>

<%#= link_to 'Back', games_path %>

app/views/games/show.html.erb
<div class="container container-show-game">
  <p id="notice"><%= notice %></p>
  <div class="columns">
    <div class="column">
      <figure class="image">
        <%=image_tag(@game.image.to_s) %>
      </figure>
    </div>
    <div class="column">
      <div class="level">
        <p><strong>Nome: </strong> <%= @game.name %></p>
      </div>
      <div class="level">
        <p><strong>Descrição: </strong><%= @game.description %></p>
      </div>
      <div class="level">
        <p><strong>Categoria: </strong><%= @game.category.name %></p>
      </div>
      <%if @game.user.id != current_user.id && @game.status != false%>
        <div class="level">
          <strong><label for="semana">Semana(s): </label></strong>
          <%= form_for @rent_games do |f| %>
            <%= f.hidden_field :game_rent ,value: @game.rentPrice, id:'rentPrice' %>
            <%= f.hidden_field :game_id, value: @game.id %>
            <%= f.number_field :week, class:'input', min: 1, id:'semana', onchange:'valorAluguel()' %>
          </div>
          <div class="level">
            <p><strong>Valor: </strong><span id="valor"><%=number_to_currency(@game.rentPrice, unit: "R$", separator: ",", delimiter:"")%></span></p>
          </div>
          <div class="level">
            <%= f.submit "Adicionar ao Carrinho", class:'button is-normal is-success is-fullwidth'%>
          <%end %>
        </div>
      <%end %>
    </div>
  </div>
</div>

<!--<%#= link_to 'Edit', edit_game_path(@game) %> |-->
<%#= link_to 'Back', games_path %>