config/routes.rb
Rails.application.routes.draw do
  post 'rents/rent_confirmation', to: 'rents#rent_confirmation', as: 'rent_confirmation'
  get 'rents/confirmation_page'
  post 'rents/:address_id', to: 'rents#set_address', as: 'set_address'
  get 'rents/addressToRent'
  get 'games/myGames'
  resources :rent_games
  root to: 'games#index'
  resources :addresses
  get 'control_users/index'
  devise_for :users
  resources :rents
  resources :games
  resources :categories
  resource :carts, only: [:show]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FANTASMA</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <nav class="navbar is-black">
      <div class="navbar-brand">
        <%= link_to root_path, class:'navbar-item' do %>
          <i class="fas fa-ghost fa-5x"></i>
        <%end %>
      </div>
      <div class="navbar-menu">
        <div class="navbar-end">
          <div class="navbar-item">
            <div class="buttons">
              <% if user_signed_in? %>
                <% if current_user.role == "admin" %>
                  <%= link_to root_path, class:'button is-primary' do %>
                    <i class="fas fa-home"></i>
                    &nbsp;Inicio
                  <% end %>
                  <%= link_to control_users_index_path, class:'button is-primary' do %>
                    <i class="fas fa-user"></i>
                    &nbsp;Usuários
                  <% end %>
                  <%= link_to rents_path, class:'button is-primary' do %>
                    <i class="fas fa-bolt"></i>
                    &nbsp;Aluguéis
                  <% end %>
                  <%= link_to categories_path, class:'button is-primary' do %>
                    <i class="fas fa-clipboard-list"></i>
                    &nbsp;Categorias de Jogos
                  <% end %>
                  <%= link_to games_myGames_path, class:'button is-primary' do %>
                    <i class="fas fa-gamepad"></i>
                    &nbsp;Meus Jogos
                  <% end %>
                  <%= link_to edit_user_registration_path, class:'button is-primary' do %>
                    <i class="fas fa-user-cog"></i>
                    &nbsp;Configuração de conta
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete, class:'button is-primary' do %>
                    <i class="fas fa-sign-out-alt"></i>
                    &nbsp;Sair
                  <% end %>
                <% end %>
                <% if current_user.role == "normal_user" %>
                  <%= link_to root_path, class:'button is-primary' do %>
                    <i class="fas fa-home"></i>
                    &nbsp;Inicio
                  <% end %>
                  <%= link_to games_myGames_path, class:'button is-primary' do %>
                    <i class="fas fa-gamepad"></i>
                    &nbsp;Meus Jogos
                  <% end %>
                  <%= link_to rents_path, class:'button is-primary' do %>
                    <i class="fas fa-bolt"></i>
                    &nbsp;Aluguéis
                  <% end %>
                  <%= link_to addresses_path, class:'button is-primary' do %>
                    <i class="fas fa-map-marked-alt"></i>
                    &nbsp;Endereços
                  <% end %>
                  <%= link_to edit_user_registration_path, class:'button is-primary' do %>
                    <i class="fas fa-user-cog"></i>
                    &nbsp;Configuração de conta
                  <% end %>
                  <%= link_to '/carts', class:'button is-primary' do %>
                    <i class="fas fa-shopping-cart"></i>
                    &nbsp;Carrinho
                  <% end %>
                  <%= link_to destroy_user_session_path, method: :delete, class:'button is-primary' do %>
                    <i class="fas fa-sign-out-alt"></i>
                    &nbsp;Sair
                  <% end %>
                <% end %>
              <% else %>
                <%= link_to new_user_session_path, class:'button is-primary' do %>
                  <i class="fas fa-user"></i>
                  &nbsp;Login
                <% end %>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </nav>
    <main>
      <div class="hero">
        <div class="hero-body">
          <%= yield %>
        </div>
      </div>
    </main>
    <footer class="footer has-text-centered">
      Fantasma
    </footer>
    <script src="https://kit.fontawesome.com/03f53d9cf6.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/2.1.1/jquery.js" integrity="sha256-FA/0OOqu3gRvHOuidXnRbcmAWVcJORhz+pv3TX2+U6w=" crossorigin="anonymous"></script>
    <%= javascript_include_tag 'jquery.correios.min' %>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery.maskedinput/1.4.1/jquery.maskedinput.min.js" integrity="sha256-+4KHeBj6I8jAKAU8xXRMXXlH+sqCvVCoK5GAFkmb+2I=" crossorigin="anonymous"></script>
    <script>
        jQuery(function($)
        {
            $('#cep').mask("99.999-999");
            correios.init( 'Bc137Cy2Ijejk2qyCmu09pUqlbWDVPKH', '3Dhr73r3DROUbk1hVvdatyFFXmHVtZ4QfSML6LZKuQZR15h2' );
            $('#cep').correios( '#address', '#district', '#city', '#uf');
        });
    </script>
  </body>
</html>